### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Naim08** [nicholastay/teemo.js#1]
Hi, I was able to get the chat-client example up and working, but I am having trouble moving forward, would you be able to have a quick chat with me? thank you

**Comment by nicholastay** [comment]
Hi, sure. What trouble do you have exactly? Judging by the issue title you gave would it be about handling commands given by a user?

**Comment by Naim08** [comment]
That's exactly what I thought. What exactly are the commands? Thank you

**Comment by nicholastay** [comment]
There are no commands by default. You must catch the event, parse the message, interpret the command and handle accordingly. Here is a small example:

```js
// ...
client.on('pm', function(from, message) {
    // Basic command parsing to get the first arg of a string
    var tail = message.split(' ');
    var command = tail.shift();
    tail = tail.join(' ');

     // ... for example
    if (command == '!hello') {
        client.pm(from, 'Hello! :D');
    }
});
```

If you want to see it used in a project you can check out my league chatbot which uses both the API and the chat: https://github.com/nicholastay/node-league-bot

As a side note I'm writing some docs right now, it should make it easier for other referencing.

**Comment by Naim08** [comment]
So I just tried the link you send me. I think I ahve a better understanding. However, when I try commands such as !ping or !gameinfo, nothing seems to work.

**Comment by nicholastay** [comment]
Hi, I'm sorry, but it turns out there was a small bug with the old logic. I haven't worked on this for a while, but now I have fixed it. I am pushing to npm now, and there are some updated docs as well.
